In [1]:
# use of bag of words

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("spam.csv")

In [5]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [9]:
df['spam'] = df.Category.apply(lambda x: 1 if x == 'spam' else 0)

In [10]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train , X_test , y_train , y_test = train_test_split(df.Message , df.spam, test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [14]:
X_test.shape

(1115,)

In [15]:
type(X_train)

pandas.core.series.Series

In [16]:
X_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

In [18]:
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7750 sparse matrix of type '<class 'numpy.int64'>'
	with 59090 stored elements in Compressed Sparse Row format>

In [20]:
X_train_cv.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
X_train_cv.shape

(4457, 7750)

In [23]:
v.get_feature_names_out()[1000:1050]

array(['ans', 'ansr', 'answer', 'answered', 'answering', 'answers',
       'answr', 'antha', 'anthony', 'anti', 'antibiotic', 'any',
       'anybody', 'anyhow', 'anymore', 'anyone', 'anyones', 'anythiing',
       'anythin', 'anything', 'anytime', 'anyway', 'anyways', 'anywhere',
       'aom', 'apart', 'apartment', 'apes', 'apeshit', 'aphex', 'apo',
       'apologetic', 'apologise', 'apology', 'app', 'apparently',
       'appear', 'appendix', 'applausestore', 'applebees', 'apples',
       'application', 'apply', 'applyed', 'applying', 'appointment',
       'appointments', 'appreciate', 'appreciated', 'approaches'],
      dtype=object)

In [24]:
X_train_np = X_train_cv.toarray()

X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv , y_train)

MultinomialNB()

In [27]:
X_test_cv = v.transform(X_test)

In [28]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

In [30]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       955
           1       0.99      0.91      0.95       160

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [34]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow? ',
'Upto 20X discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [35]:
email_count = v.transform(emails)

In [36]:
model.predict(email_count)

array([0, 1], dtype=int64)

In [37]:
# using pipeline

In [38]:
from sklearn.pipeline import Pipeline

In [39]:
clf = Pipeline([
    ('vectrizer' , CountVectorizer()),
    ('nb', MultinomialNB())
])

In [40]:
clf.fit(X_train , y_train)

Pipeline(steps=[('vectrizer', CountVectorizer()), ('nb', MultinomialNB())])

In [44]:
print(classification_report(y_test , clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       955
           1       0.99      0.91      0.95       160

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

